apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-zwk0
  namespace: amobrem-tenant
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:amobrem-tenant-devfile-sample-code-with-quarkus-zwk0
        name: my-java-quarkus
        resources: {}
status: {}
